### ISSUE TITLE
Contoh API detailnya

### ISSUE THREAD

**Issue by mdestafadilah** [ahsai001/wa-api#2]
Halo pak,

> api untuk kirim pesan teks ke nomor wa tertentu

bisa dicontohkan detailnya seperti apa pak?

Terima kasih.

**Comment by ahsai001** [comment]
sudah ada contohnya di file-file html yang ada di folder public mas

**Comment by mdestafadilah** [comment]
> sudah ada contohnya di file-file html yang ada di folder public mas

```javascript
          url: "http://localhost/send-text",
          type: "POST",
          data: formData,
```

ini ya pak? jadi tinggal tambahan `URL_API/send-text` ya?

**Comment by mdestafadilah** [comment]
bisa pak, terima kasih ya.
